population=c(50,50,120)
labels=c("lion","tiger","hen")
myCol=c("yellow","red","green")
png("1.png")
barplot(population,col=myCol,names.arg=labels,main="Bar Diagram ",xlab="animals",ylab="Population")
legend("topright",labels,fill=myCol)
dev.off()
